services:
  web:
    image: nginx
    container_name: th_web
    restart: always
    depends_on:
    - app
    ports:
    - "80:80"
    - "443:443"
    volumes:
    # Use this for testing the prod container locally:
    #- ./docker/certs:/etc/letsencrypt/live/tiddlyhost.com:Z
    - ./docker/letsencrypt:/etc/letsencrypt:Z

    - ./docker/nginx-conf-prod:/etc/nginx/conf.d:Z
    - rails-static:/opt/rails-static

  app:
    image: sbaird/tiddlyhost:latest
    container_name: th_app
    restart: always
    depends_on:
    - db
    - cache
    environment:
      RAILS_MASTER_KEY:

    volumes:
    - ./docker/log:/var/log/app:Z
    - ./docker/prerelease.html:/opt/app/tw_content/empties/prerelease.html:Z
    - rails-static:/opt/app/public

    build:
      context: .
      dockerfile: docker/Dockerfile.prod

  cache:
    image: memcached
    container_name: th_cache
    command: memcached -I 8M

  db:
    image: postgres:13
    container_name: th_db
    restart: always
    environment:
      POSTGRES_PASSWORD: notsecure123
    volumes:
    - ./docker/postgresql-data/data:/var/lib/postgresql/data:Z

volumes:
  # Share rails public with nginx so it can serve static files directly
  rails-static:
    name: th_rails_static
