services:
  web:
    image: nginx
    restart: always
    depends_on:
    - prod
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./docker/letsencrypt:/etc/letsencrypt:Z
    - ./docker/nginx-conf-prod:/etc/nginx/conf.d:Z

  prod:
    image: sbaird/tiddlyhost:latest
    restart: always
    depends_on:
    - db
    - cache
    environment:
      RAILS_MASTER_KEY:

    volumes:
    - ./docker/log:/var/log/app:Z

    build:
      context: .
      dockerfile: docker/Dockerfile.prod

  cache:
    image: memcached

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: notsecure123
    volumes:
    - ./docker/postgresql-data/data:/var/lib/postgresql/data:Z
