services:
  web:
    image: nginx
    container_name: th_web
    depends_on:
    - app
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./docker/certs:/etc/letsencrypt/live/tiddlyhost.com:Z
    - ./docker/nginx-conf-local:/etc/nginx/conf.d:Z

  app:
    image: base:latest
    container_name: th_app
    depends_on:
    - db
    - cache
    volumes:
    - ./rails:/opt/app:Z
    - ./docker/log:/var/log/app:Z
    command: /bin/start-rails.sh

    build:
      context: .
      dockerfile: docker/Dockerfile.base
      args:
      - USER_ID
      - GROUP_ID

  cache:
    image: memcached
    container_name: th_cache
    command: memcached -I 8M

  db:
    image: postgres:13
    container_name: th_db
    environment:
      POSTGRES_PASSWORD: notsecure123
    # So we can use localhost for the rails db when running
    # on bare metal rather than in the app container
    ports:
    - "5432:5432"
    volumes:
    - ./docker/postgresql-data/data:/var/lib/postgresql/data:Z
