
- hosts: all
  become: yes
  become_user: root

  vars:
    certbot_dns_credentials: ../etc/certbot-dns-user-credentials.yml
    docker_config_json: ../etc/docker-conf/config.json
    docker_compose_file: ../docker-compose-prod.yml
    master_key_file: ../rails/config/master.key
    credentials_file: ../rails/config/credentials.yml.enc
    nginx_conf_src_dir: ../docker/nginx-conf-prod/
    nginx_conf_files:
    - app.conf
    - commonconf

    cert_host: tiddlyhost.com
    extra_cert_host: tiddlyspot.com
    certbot_dir_config: "{{ docker_dir }}/letsencrypt"
    certbot_dir_work: "{{ home_dir }}/.certbot/work"
    certbot_dir_logs: "{{ home_dir }}/.certbot/logs"
    certbot_dir_live: "{{ certbot_dir_config }}/live/{{ cert_host }}"
    certbot_notification_email: simon.baird@gmail.com

    thost_log_dir: "{{ docker_dir }}/log"
    nginx_conf_dir: "{{ docker_dir }}/nginx-conf-prod"
    secrets_dir: "{{ docker_dir }}/secrets"

    service_name: thost
    db_name: app_production
    db_user: postgres

  tasks:

  - name: Add repo for docker-ce
    command:
      cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      creates: /etc/yum.repos.d/docker-ce.repo
      warn: false
    tags:
    - deps

  - name: Install docker and a few other packages we need
    dnf:
      state: present
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - certbot
      - chkconfig
      - make
      - cronie
      - nmap-ncat
    tags:
    - deps

  - name: Start docker service
    systemd:
      name: docker
      state: started
      enabled: yes
    tags:
    - deps

  - name: Start crond
    systemd:
      name: crond
      state: started
      enabled: yes
    tags:
    - deps

  - name: Pip install docker-compose and certbot-dns-route53
    pip:
      name:
      - docker-compose
      - certbot-dns-route53
    tags:
    - deps

  - name: Make .docker dir for root user
    file:
      path: "{{ root_home_dir }}/.docker"
      state: directory
    tags:
    - deps

  - name: Copy config.json file for docker pull credentials
    copy:
      src: "{{ docker_config_json }}"
      dest: "{{ root_home_dir }}/.docker/config.json"
      mode: "0600"
    tags:
    - deps

  - name: Create dir for certbot aws credentials
    become: no
    file:
      path: "{{ home_dir }}/.aws"
      state: directory
    tags:
    - certs

  - name: Install AWS credentials for certbot
    become: no
    copy:
      src: "{{ certbot_dns_credentials }}"
      dest: "{{ home_dir }}/.aws/credentials"
      mode: "0600"
    tags:
    - certs

  - name: Create a cert if it doesn't exist
    become: no
    command:
      cmd: "{{ bin_dir }}/certbot-create"
      creates: "{{ certbot_dir_live }}/fullchain.pem"
    tags:
    - certs

  - name: Renew certs maybe
    become: no
    command:
      cmd: "{{ bin_dir }}/certbot-renew"
    register: certbot_renew
    tags:
    - certs

  - name: Show renew output
    debug:
      var: certbot_renew.stdout_lines
    tags:
    - certs

  - name: Copy docker-compose file
    become: no
    copy:
      src: "{{ docker_compose_file }}"
      dest: "{{ home_dir }}/docker-compose.yml"
    tags:
    - app

  - name: Pull latest images
    # So docker-compose doesn't try to build
    command:
      cmd: docker-compose pull -q
    tags:
    - app
    - fast-upgrade

  - name: Create dir for logs
    become: no
    file:
      path: "{{ thost_log_dir }}"
      state: directory
    tags:
    - app

  - name: Create nginx conf dir
    become: no
    file:
      path: "{{ nginx_conf_dir }}"
      state: directory
    tags:
    - app

  - name: Copy nginx config
    become: no
    copy:
      src: "{{ nginx_conf_src_dir }}/{{ item }}"
      dest: "{{ nginx_conf_dir }}/{{ item }}"
      mode: "0600"
    with_items: "{{ nginx_conf_files }}"
    tags:
    - app

  - name: Create dir for secrets
    become: no
    file:
      path: "{{ secrets_dir }}"
      state: directory
    tags:
    - app

  - name: Copy master key file
    become: no
    copy:
      src: "{{ master_key_file }}"
      dest: "{{ secrets_dir }}/master.key"
      mode: "0400"
    tags:
    - app

  - name: Copy encrypted credentials file
    become: no
    copy:
      src: "{{ credentials_file }}"
      dest: "{{ secrets_dir }}/credentials.yml.enc"
      mode: "0400"
    tags:
    - app

  - name: Copy init script
    template:
      src: templates/etc/init.d/{{ service_name }}.j2
      dest: /etc/init.d/{{ service_name }}
      mode: "0755"
    register: init_script
    tags:
    - app

  - name: Run systemctl daemon-reload if required
    command:
      cmd: systemctl daemon-reload
    when: init_script.changed
    tags:
    - app

  - name: Start/restart service
    systemd:
      name: "{{ service_name }}"
      state: restarted
    tags:
    - app
    - fast-upgrade

  - name: Apply database migrations
    command:
      cmd: docker-compose exec app bash -c "bin/rails db:migrate"
    register: db_migrate
    tags:
    - app
    - fast-upgrade
    - migration

  - name: Show database migration output
    debug:
      var: db_migrate.stdout_lines
    tags:
    - app
    - fast-upgrade
    - migration

  - name: Create bin dir
    become: no
    file:
      path: "{{ bin_dir }}"
      state: directory
    tags:
    - scripts

  - name: Copy up a Makefile and some scripts
    become: no
    template:
      src: templates/{{ item }}.j2
      dest: "{{ home_dir }}/{{ item }}"
      mode: "0755"
    with_items:
    - Makefile
    - bin/certbot-create
    - bin/certbot-renew
    - bin/db-backup
    - bin/fetch-prerelease-empty
    tags:
    - scripts

    # (These are in a different place because they're also useful locally)
  - name: Copy cache info scripts
    become: no
    copy:
      src: "../bin/{{ item }}"
      dest: "{{ bin_dir }}/{{ item }}"
      mode: "0755"
    with_items:
    - cache-info
    - cache-list-items
    tags:
    - scripts

  - name: Create a cron job for regular db backups
    cron:
      name: thost db backup
      user: root
      job: "{{ bin_dir }}/db-backup"
      minute: "5"
      hour: "*/8"
    tags:
    - scripts

  - name: Create a cron job for regular prerelease empty fetches
    cron:
      name: fetch prerelease empty
      user: "{{ ansible_user }}"
      job: "{{ bin_dir }}/fetch-prerelease-empty"
      minute: "4"
      hour: "*/8"
    tags:
    - scripts

  - name: Fetch latest prerelease
    command:
      cmd: "{{ bin_dir }}/fetch-prerelease-empty"
    tags:
    - app
    - fast-upgrade
    - refresh-prerelease

  - name: Clean up unused docker images
    command:
      cmd: docker image prune -f
    tags:
    - cleanup

  - name: Clean up stale containers
    command:
      cmd: docker-compose rm
    tags:
    - cleanup
